### ISSUE TITLE
Horovod with pytorch issue

### ISSUE THREAD

**Issue by sharmaannapurna** [IntuitionMachines/OrigamiNet#6]
Hi, 
I followed all installation as suggested by the repository readme file. It gave me following error when I tried to run it :+1: 

 File "train.py", line 12, in <module>
    check_extension('horovod.torch', 'HOROVOD_WITH_PYTORCH', __file__, 'mpi_lib_v2')
  File "/home/annapurna/anaconda3/envs/origami/lib/python3.6/site-packages/horovod/common/util.py", line 56, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    check_extension('horovod.torch', 'HOROVOD_WITH_PYTORCH', __file__, 'mpi_lib', '_mpi_lib')
  File "/home/annapurna/anaconda3/envs/origami/lib/python3.6/site-packages/horovod/common/util.py", line 56, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

Please suggest as to what has gone wrong?
I tried to install horovod with pytorch as well but still facing the same issue.

**Comment by kapitsa2811** [comment]
1+
